version: '3'
services:
  db:
    image: mariadb:10.6.8
    container_name: rgt
    restart: always
    ports:
      - 23306:3306
    env_file: .env.db.docker
    # 볼륨생성 & 바인드마운트
    volumes:
      # Docker 컨테이너 최초 실행 시 작동시킬 스크립트들(주로 데이터 생성)
      - ./db/maria/init:/docker-entrypoint-initdb.d
      # 실제 DB 데이터
      - ./db/maria/data:/var/lib/mysql
      # MySQL 서버의 구성 설정. MySQL 서버가 시작될때마다 실행
      - ./db/maria/conf:/etc/mysql/conf.d